"use client";

import { Badge, Button, Card, CardHeader, DataTable, Dialog, EmptyState, Field, Input, Select, type DataColumn } from "@eduhub/ui";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BookOpen, CalendarDays, CalendarRange, Pencil, Plus, Power, Shapes } from "lucide-react";
import { useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { ErrorPanel, LoadingPanel } from "@/components/api-panel";
import { PageHeader } from "@/components/page-header";
import { sessionErrorMessage, useSession } from "@/components/session-provider";
import type { AcademicYearDto, Envelope, PagedEnvelope, SemesterDto, SubjectDto } from "@/lib/domain";
import { formatDate, statusLabel, statusTone } from "@/lib/domain";

type AcademicTab = "years" | "semesters" | "subjects";

/** AcademicManagement quản lý năm học, học kỳ và môn học theo ba bảng liên quan. */
export function AcademicManagement() {
  const { request } = useSession();
  const queryClient = useQueryClient();
  const [tab, setTab] = useState<AcademicTab>("years");
  const [createOpen, setCreateOpen] = useState(false);
  const [editingSubject, setEditingSubject] = useState<SubjectDto | null>(null);
  const years = useQuery({ queryKey: ["academic-years"], queryFn: () => request<PagedEnvelope<AcademicYearDto>>("/api/v1/academic-years?page=1&pageSize=100") });
  const semesters = useQuery({ queryKey: ["semesters"], queryFn: () => request<PagedEnvelope<SemesterDto>>("/api/v1/semesters?page=1&pageSize=100") });
  const subjects = useQuery({ queryKey: ["subjects", "all"], queryFn: () => request<PagedEnvelope<SubjectDto>>("/api/v1/subjects?page=1&pageSize=100") });
  const yearForm = useForm<{ name: string; startDate: string; endDate: string }>({ defaultValues: { name: "", startDate: "", endDate: "" } });
  const semesterForm = useForm<{ academicYearId: string; name: string; startDate: string; endDate: string; gradeEntryFrom: string; gradeEntryTo: string }>({ defaultValues: { academicYearId: "", name: "", startDate: "", endDate: "", gradeEntryFrom: "", gradeEntryTo: "" } });
  const subjectForm = useForm<{ subjectCode: string; name: string; credits: number; maxScore: number }>({ defaultValues: { subjectCode: "", name: "", credits: 3, maxScore: 10 } });
  const editSubjectForm = useForm<{ name: string; credits: number; maxScore: number }>({ defaultValues: { name: "", credits: 3, maxScore: 10 } });

  const createYear = useMutation({ mutationFn: (value: { name: string; startDate: string; endDate: string }) => request<Envelope<AcademicYearDto>>("/api/v1/academic-years", { method: "POST", body: JSON.stringify(value) }), onSuccess: () => finish("Đã tạo năm học.", "academic-years", yearForm.reset), onError: fail });
  const createSemester = useMutation({ mutationFn: (value: Record<string, unknown>) => request<Envelope<SemesterDto>>("/api/v1/semesters", { method: "POST", body: JSON.stringify(value) }), onSuccess: () => finish("Đã tạo học kỳ.", "semesters", semesterForm.reset), onError: fail });
  const createSubject = useMutation({ mutationFn: (value: Record<string, unknown>) => request<Envelope<SubjectDto>>("/api/v1/subjects", { method: "POST", body: JSON.stringify(value) }), onSuccess: () => finish("Đã tạo môn học.", "subjects", subjectForm.reset), onError: fail });
  const updateSubject = useMutation({ mutationFn: (value: { name: string; credits: number; maxScore: number }) => { if (!editingSubject) throw new Error("Chưa chọn môn học."); return request<Envelope<SubjectDto>>(`/api/v1/subjects/${editingSubject.id}`, { method: "PUT", body: JSON.stringify(value) }); }, onSuccess: async () => { toast.success("Đã cập nhật môn học."); setEditingSubject(null); await queryClient.invalidateQueries({ queryKey: ["subjects"] }); }, onError: fail });
  const disableSubject = useMutation({ mutationFn: (subject: SubjectDto) => request<Envelope<SubjectDto>>(`/api/v1/subjects/${subject.id}/disable`, { method: "PUT" }), onSuccess: async () => { toast.success("Đã vô hiệu hóa môn học."); await queryClient.invalidateQueries({ queryKey: ["subjects"] }); }, onError: fail });

  function fail(error: unknown) { toast.error(sessionErrorMessage(error)); }
  async function finish(message: string, key: string, reset: () => void) { toast.success(message); setCreateOpen(false); reset(); await queryClient.invalidateQueries({ queryKey: [key] }); }
  const openCreate = (nextTab: AcademicTab) => { setTab(nextTab); setCreateOpen(true); };
  const yearItems = useMemo(() => years.data?.data.items || [], [years.data]);
  const semesterItems = semesters.data?.data.items || [];
  const subjectItems = subjects.data?.data.items || [];

  const yearColumns = useMemo<DataColumn<AcademicYearDto>[]>(() => [{ key: "name", header: "Năm học", cell: (row) => <div className="entity-cell"><span><CalendarRange size={17} /></span><div><b>{row.name}</b><small>{row.id.slice(0, 8)}...</small></div></div> }, { key: "period", header: "Thời gian", cell: (row) => `${formatDate(row.startDate)} – ${formatDate(row.endDate)}` }, { key: "status", header: "Trạng thái", cell: (row) => <Badge tone={statusTone(row.status)}>{statusLabel(row.status)}</Badge> }], []);
  const semesterColumns = useMemo<DataColumn<SemesterDto>[]>(() => [{ key: "name", header: "Học kỳ", cell: (row) => <div className="entity-cell"><span><CalendarDays size={17} /></span><div><b>{row.name}</b><small>{yearItems.find((year) => year.id === row.academicYearId)?.name || "Năm học"}</small></div></div> }, { key: "period", header: "Thời gian", cell: (row) => `${formatDate(row.startDate)} – ${formatDate(row.endDate)}` }, { key: "entry", header: "Cửa sổ nhập điểm", cell: (row) => `${formatDate(row.gradeEntryFrom)} – ${formatDate(row.gradeEntryTo)}` }, { key: "status", header: "Trạng thái", cell: (row) => <Badge tone={statusTone(row.status)}>{statusLabel(row.status)}</Badge> }], [yearItems]);
  const subjectColumns = useMemo<DataColumn<SubjectDto>[]>(() => [{ key: "subject", header: "Môn học", cell: (row) => <div className="entity-cell"><span><BookOpen size={17} /></span><div><b>{row.name}</b><small>{row.subjectCode}</small></div></div> }, { key: "credits", header: "Tín chỉ", cell: (row) => row.credits }, { key: "max", header: "Thang điểm", cell: (row) => row.maxScore }, { key: "status", header: "Trạng thái", cell: (row) => <Badge tone={row.isActive ? "success" : "neutral"}>{row.isActive ? "Đang dùng" : "Đã tắt"}</Badge> }, { key: "actions", header: "", className: "table-action", cell: (row) => <div className="row-actions"><button className="ui-icon-button" title={`Sửa ${row.name}`} aria-label={`Sửa ${row.name}`} onClick={() => { setEditingSubject(row); editSubjectForm.reset({ name: row.name, credits: row.credits, maxScore: row.maxScore }); }}><Pencil size={16} /></button>{row.isActive ? <button className="ui-icon-button danger-icon" title={`Vô hiệu hóa ${row.name}`} aria-label={`Vô hiệu hóa ${row.name}`} onClick={() => disableSubject.mutate(row)}><Power size={16} /></button> : null}</div> }], [disableSubject, editSubjectForm]);

  if (years.isLoading || semesters.isLoading || subjects.isLoading) return <><PageHeader eyebrow="DỮ LIỆU HỌC VỤ" title="Năm học & Môn học" /><LoadingPanel rows={8} /></>;
  const error = years.error || semesters.error || subjects.error;
  if (error) return <><PageHeader eyebrow="DỮ LIỆU HỌC VỤ" title="Năm học & Môn học" /><ErrorPanel message={sessionErrorMessage(error)} onRetry={() => { void years.refetch(); void semesters.refetch(); void subjects.refetch(); }} /></>;
  const current = tab === "years" ? { title: "Danh sách năm học", description: `${yearItems.length} năm học`, columns: yearColumns, rows: yearItems as unknown[] } : tab === "semesters" ? { title: "Danh sách học kỳ", description: `${semesterItems.length} học kỳ`, columns: semesterColumns, rows: semesterItems as unknown[] } : { title: "Danh sách môn học", description: `${subjectItems.length} môn học`, columns: subjectColumns, rows: subjectItems as unknown[] };

  return <div className="page-stack"><PageHeader eyebrow="DỮ LIỆU HỌC VỤ" title="Năm học & Môn học" description="Thiết lập dữ liệu nền trước khi tạo lớp, ghi danh và cấu hình điểm." actions={<Button onClick={() => openCreate(tab)}><Plus size={17} /> {tab === "years" ? "Thêm năm học" : tab === "semesters" ? "Thêm học kỳ" : "Thêm môn học"}</Button>} />
    <div className="segmented-tabs" role="tablist" aria-label="Loại dữ liệu học vụ"><button role="tab" aria-selected={tab === "years"} onClick={() => setTab("years")}><CalendarRange size={16} /> Năm học</button><button role="tab" aria-selected={tab === "semesters"} onClick={() => setTab("semesters")}><CalendarDays size={16} /> Học kỳ</button><button role="tab" aria-selected={tab === "subjects"} onClick={() => setTab("subjects")}><Shapes size={16} /> Môn học</button></div>
    <Card><CardHeader title={current.title} description={current.description} />{tab === "years" ? <DataTable columns={yearColumns} rows={yearItems} rowKey={(row) => row.id} empty={<EmptyState icon={CalendarRange} title="Chưa có năm học" description="Tạo năm học trước khi thiết lập học kỳ." />} /> : tab === "semesters" ? <DataTable columns={semesterColumns} rows={semesterItems} rowKey={(row) => row.id} empty={<EmptyState icon={CalendarDays} title="Chưa có học kỳ" description="Chọn năm học và tạo học kỳ đầu tiên." />} /> : <DataTable columns={subjectColumns} rows={subjectItems} rowKey={(row) => row.id} empty={<EmptyState icon={BookOpen} title="Chưa có môn học" description="Thêm môn học để tiếp tục phân công và cấu hình điểm." />} />}</Card>

    <Dialog open={createOpen} onOpenChange={setCreateOpen} title={tab === "years" ? "Thêm năm học" : tab === "semesters" ? "Thêm học kỳ" : "Thêm môn học"} description="Các trường bắt buộc phải khớp dữ liệu vận hành thực tế." footer={<><Button variant="ghost" onClick={() => setCreateOpen(false)}>Hủy</Button><Button form={`create-${tab}-form`} type="submit" loading={createYear.isPending || createSemester.isPending || createSubject.isPending}>Lưu dữ liệu</Button></>}>
      {tab === "years" ? <form id="create-years-form" className="dialog-form" onSubmit={yearForm.handleSubmit((value) => createYear.mutate(value))}><Field label="Tên năm học" htmlFor="yearName" required><Input id="yearName" placeholder="2026–2027" {...yearForm.register("name", { required: true })} /></Field><div className="form-grid-2"><Field label="Ngày bắt đầu" htmlFor="yearStart" required><Input id="yearStart" type="date" {...yearForm.register("startDate", { required: true })} /></Field><Field label="Ngày kết thúc" htmlFor="yearEnd" required><Input id="yearEnd" type="date" {...yearForm.register("endDate", { required: true })} /></Field></div></form> : null}
      {tab === "semesters" ? <form id="create-semesters-form" className="dialog-form" onSubmit={semesterForm.handleSubmit((value) => createSemester.mutate(value))}><Field label="Năm học" htmlFor="semesterYear" required><Select id="semesterYear" {...semesterForm.register("academicYearId", { required: true })}><option value="">Chọn năm học</option>{yearItems.map((year) => <option value={year.id} key={year.id}>{year.name}</option>)}</Select></Field><Field label="Tên học kỳ" htmlFor="semesterName" required><Input id="semesterName" placeholder="Học kỳ I" {...semesterForm.register("name", { required: true })} /></Field><div className="form-grid-2"><Field label="Bắt đầu" htmlFor="semesterStart" required><Input id="semesterStart" type="date" {...semesterForm.register("startDate", { required: true })} /></Field><Field label="Kết thúc" htmlFor="semesterEnd" required><Input id="semesterEnd" type="date" {...semesterForm.register("endDate", { required: true })} /></Field><Field label="Mở nhập điểm" htmlFor="gradeFrom" required><Input id="gradeFrom" type="date" {...semesterForm.register("gradeEntryFrom", { required: true })} /></Field><Field label="Đóng nhập điểm" htmlFor="gradeTo" required><Input id="gradeTo" type="date" {...semesterForm.register("gradeEntryTo", { required: true })} /></Field></div></form> : null}
      {tab === "subjects" ? <form id="create-subjects-form" className="dialog-form" onSubmit={subjectForm.handleSubmit((value) => createSubject.mutate(value))}><div className="form-grid-2"><Field label="Mã môn" htmlFor="subjectCode" required><Input id="subjectCode" placeholder="MATH" {...subjectForm.register("subjectCode", { required: true })} /></Field><Field label="Tên môn" htmlFor="subjectName" required><Input id="subjectName" placeholder="Toán học" {...subjectForm.register("name", { required: true })} /></Field><Field label="Tín chỉ" htmlFor="credits" required><Input id="credits" type="number" min="1" {...subjectForm.register("credits", { valueAsNumber: true, required: true })} /></Field><Field label="Thang điểm" htmlFor="maxScore" required><Input id="maxScore" type="number" min="1" step="0.1" {...subjectForm.register("maxScore", { valueAsNumber: true, required: true })} /></Field></div></form> : null}
    </Dialog>

    <Dialog open={Boolean(editingSubject)} onOpenChange={(open) => { if (!open) setEditingSubject(null); }} title="Cập nhật môn học" description={editingSubject ? `${editingSubject.subjectCode} · ${editingSubject.name}` : undefined} footer={<><Button variant="ghost" onClick={() => setEditingSubject(null)}>Hủy</Button><Button type="submit" form="edit-subject-form" loading={updateSubject.isPending}>Lưu thay đổi</Button></>}><form id="edit-subject-form" className="dialog-form" onSubmit={editSubjectForm.handleSubmit((value) => updateSubject.mutate(value))}><Field label="Tên môn" htmlFor="editSubjectName" required><Input id="editSubjectName" {...editSubjectForm.register("name", { required: true })} /></Field><div className="form-grid-2"><Field label="Tín chỉ" htmlFor="editCredits" required><Input id="editCredits" type="number" min="1" {...editSubjectForm.register("credits", { valueAsNumber: true })} /></Field><Field label="Thang điểm" htmlFor="editMaxScore" required><Input id="editMaxScore" type="number" min="1" step="0.1" {...editSubjectForm.register("maxScore", { valueAsNumber: true })} /></Field></div></form></Dialog>
  </div>;
}
